version: '3'
services:
  web:
    build:
      context: .
      dockerfile: DockerfileAngular.dev
    ports: 
      - "4200:4200"
    volumes:
      - /app/node_modules
      - .:/app
networks:
    default:
        driver: bridge
        name: Web_Server_Network