version: '3'
services:
  web:
    build:
      context: .
      dockerfile: DockerfileExpress.dev
    ports: 
      - "8080:8080"
    volumes:
      - /app/node_modules
      - .:/app
 networks:
    default:
        driver: bridge
        name: Web_Server_Network